#cloud-config

write_files:
  - path: /var/apps/ingress/docker-compose.yml
    encoding: b64
    content: ${docker-compose-config}

runcmd:
  - echo "IS_WEB_UI_ENABLED=true" > /var/apps/ingress/.env
  - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /var/apps/ingress:/var/apps/ingress -w /var/apps/ingress docker/compose:1.27.4 up -d
