#cloud-config

write_files:
  - path: /etc/profile.d/alias.sh
    content: |
      alias docker-compose='/usr/bin/docker exec -w $(pwd) docker-compose docker-compose'
  
  - path: /etc/profile.env
    content: |
      export PATH=$PATH:/var/lib/toolbox
      export ROOTPATH=$ROOTPATH:/var/lib/toolbox
  
  - path: /var/lib/toolbox/docker-compose
    permissions: '0755'
    content: |
      #!/bin/bash
      /usr/bin/docker exec -w $(pwd) docker-compose docker-compose $@
  
  %{ for file in fileset("platform_apps/", "**") ~}
  
  - path: /var/apps/${file}
    encoding: b64
    content: ${filebase64("platform_apps/${file}")}
  %{ endfor ~}
  %{ for app in platform_apps ~}
  
  - path: /var/apps/${app.app_name}/.env
    encoding: b64
    content: ${base64encode("${app.env_file_content}\n")}
  %{ endfor ~}
  
  - path: /etc/systemd/system/docker-compose.service
    content: |
      [Unit]
      Description=Start platform app: docker-compose

      [Service]
      Environment="HOME=/var/apps/docker-compose"
      ExecStart=/usr/bin/docker run --name="docker-compose" --rm -v /var/run/docker.sock:/var/run/docker.sock -v "/var/apps:/var/apps" -w "/var/apps" docker/compose:1.27.4 sh -c "while true; do sleep 10000; done"
      ExecStop=/usr/bin/docker stop docker-compose
  %{ for file in fileset("platform_apps/", "**/docker-compose.yml") ~}
  
  - path: /etc/systemd/system/${basename(dirname("${file}"))~}.service
    content: |
      [Unit]
      Description=Platform app: ${basename(dirname("${file}"))~}
  
      [Service]
      Environment="HOME=${dirname("/var/apps/${file}")~}"
      ExecStart=docker-compose up -d
      ExecStop=docker-compose down --remove-orphans
  %{ endfor ~}

runcmd:
  - systemctl daemon-reload
  - source /etc/profile.d/alias.sh
  - systemctl start docker-compose.service
  %{ for file in fileset("platform_apps/", "**/docker-compose.yml") ~}
  
  - systemctl start ${basename(dirname("${file}"))~}.service
  %{ endfor ~}

output: 
  all: '/var/log/cloud-init.log'
