#cloud-config

write_files:
  %{ for file in fileset("platform_apps/", "**") ~}
  
  - path: /var/apps/${file}
    encoding: b64
    content: ${filebase64("platform_apps/${file}")}
  %{ endfor ~}
  %{ for app in platform_apps ~}
  
  - path: /var/apps/${app.app_name}/.env
    content: "${app.env_file_content}\n"
  %{ endfor ~}

runcmd:
  %{ for file in fileset("platform_apps/", "**/docker-compose.yml") ~}
   
  - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /var/apps:/var/apps -w /var/apps docker/compose:1.27.4 -f ${file} up -d
  %{ endfor ~}
