output:
    init:
        output: "> /var/log/cloud-init/cloud-init.out"
        error: "> /var/log/cloud-init/cloud-init.err"
    config: "tee -a /var/log/cloud-init/cloud-config.log"
    final:
        - ">> /var/log/cloud-init/cloud-final.out"
        - "/var/log/cloud-init/cloud-final.err"
write_files:
  - path: /apps/ingress/docker-compose.yml
    permissions: 0644
    content: "${file("ingress/docker-compose.yml")}"
runcmd:
  - docker-compose -f /apps/ingress/docker-compose.yml up -d
