#cloud-config

write_files:
  %{ for file in fileset("platform_apps/", "**") ~}
  
  - path: /var/apps/${file}
    encoding: b64
    content: ${filebase64("platform_apps/${file}")}
  %{ endfor ~}
  %{ for app in platform_apps ~}
  
  - path: /var/apps/${app.app_name}/.env
    encoding: b64
    content: ${base64encode("${app.env_file_content}\n")}
  %{ endfor ~}

runcmd:
  %{ for file in fileset("platform_apps/", "**/docker-compose.yml") ~}
   
  - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v "${dirname("/var/apps/${file}")~}:${dirname("/var/apps/${file}")~} -w ${dirname("/var/apps/${file}")~} docker/compose:1.27.4 up -d >> /var/log/runcmd.log
  %{ endfor ~}
