#cloud-config

write_files:
  %{ for app in platform_apps ~}
  
  - path: /var/apps/${app.app_name}/docker-compose.yml
    encoding: b64
    content: ${filebase64("ingress/docker-compose.yml")}
  - path: /var/apps/${app.app_name}/.env
    content: ${app.dot_env_file_content}
  %{ endfor ~}

runcmd:
  - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /var/apps/ingress:/var/apps/ingress -w /var/apps/ingress docker/compose:1.27.4 up -d
