---
version: "3.7"

services:
  nginx:
    image: "nginx:latest"
    labels:
      - "traefik.http.routers.index.rule=Host(`${INDEX_HOSTNAME}`) && Path(`/`)"
    networks:
      - ingress
    environment:
      - INDEX_HOSTNAME
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html

networks:
  ingress:
    external: true
