---
version: "3.7"

services:
  nginx:
    image: "nginx:latest"
    labels:
      - "traefik.http.routers.index.rule=Host(`${INDEX_HOSTNAME}`)"
    networks:
      - ingress
    environment:
      - INDEX_HOSTNAME
    volumes:
      - ./conf.d:/etc/nginx/conf.d

networks:
  ingress:
    external: true
