---
version: "3.7"

services:
  php:
    image: "antonmarin/want2watch:latest"
    labels:
      - "traefik.http.routers.want2watch.rule=Host(`${WANT2WATCH_HOSTNAME}`) && PathPrefix(`${WANT2WATCH_PATH}`)"
      - "traefik.http.middlewares.want2watch-stripprefix.stripprefix.prefixes=/want2watch,/want2watch/"
      - "traefik.http.routers.want2watch.middlewares=want2watch-stripprefix"
    networks:
      - ingress
    environment:
      - WANT2WATCH_HOSTNAME
      - WANT2WATCH_PATH
    command: [ "php", "-S", "0.0.0.0:9000", "-t", "/app/public" ]

networks:
  ingress:
    external: true
