---
version: "3.7"

services:
  php:
    image: "antonmarin/want2watch:latest"
    labels:
      - "traefik.http.routers.want2watch.rule=Host(`${WANT2WATCH_HOSTNAME}`) && PathPrefix(`${WANT2WATCH_PATH}`)"
      - "traefik.http.middlewares.want2watch-stripprefix.stripprefix.prefixes=${WANT2WATCH_PATH},${WANT2WATCH_PATH}/"
      - "traefik.http.routers.want2watch.middlewares=want2watch-stripprefix"
      - "traefik.http.routers.want2watch.tls=true"
      - "traefik.http.routers.want2watch.tls.certresolver=letsencrypt"
    networks:
      - ingress
    environment:
      - APP_ENV=prod
      - APP_DEBUG=0
      - GLIDE_PASS
      - WANT2WATCH_HOSTNAME
      - WANT2WATCH_PATH
    command: [ "php", "-S", "0.0.0.0:9000", "-t", "/app/public" ]

networks:
  ingress:
    external: true
